--- name:default
# Calibration parameters for the camera, which are used to undistort and are added as attributes to the frames
camera_calibration:
  fx: .nan
  fy: .nan
  cx: .nan
  cy: .nan
  d0: .nan
  d1: .nan
  d2: .nan
  d3: .nan
  width: -1
  height: -1 
  ex: .nan
  ey: .nan
# Configuration parameter for Apriltags detector
#               @param bool debug // Enable debugging output (slow)
#   		      @param bool quiet // Reduce output
#         	  @param family_t family // Tag family to use
#         	                         // TAG25H7, TAG25H9, TAG36H10, 
#         	                         // TAG36H11, TAG36ARTOOLKIT
#         	                         // are possible values.
#         	  @param int border // Set tag family border size
#               @param int iters // Repeat processing on input set this many times
#               @param int threads // Use this many CPU threads
#               @param double decimate // Decimate input image by this factor
#               @param double blur // Apply low-pass blur to input
#               @param bool refine_edges // Spend more time trying to align edges of tags
#               @param bool refine_decode // Spend more time trying to decode tags
#               @param bool refine_pose // Spend more time trying to precisely localize tags
conf_param:
  debug: false
  quiet: false
  family: :TAG36H11
  border: 1
  iters: 1
  threads: 4
  decimate: 1.0
  blur: 0.0
  refine_edges: true
  refine_decode: false
  refine_pose: false
# Write the image on the output_port
draw_image: true
# Value of the marker in meters
marker_size: -1

--- name:beamsplitter
camera_calibration:
  fx: 766.536025127154
  fy: 767.5749459126396
  cx: 291.0503512057777
  cy: 227.4060484950132
  d0: -0.36965913545735024
  d1: 0.17414034009883844
  d2: 0.003915245015812422
  d3: 0.003666687416655559
  width: 640
  height: 480
  ex: .nan
  ey: .nan
  fisheye: false
marker_size: 0.156
conf_param:
  debug: false
  quiet: true
  family: :TAG36H11
  border: 1
  iters: 1
  threads: 4
  decimate: 1.0
  blur: 1.0
  refine_edges: true
  refine_decode: false
  refine_pose: false
pose_calculation: true
stretch_contrast: true
draw_debug_image: true
scale_image: 1.0


