# SIMULATION
--- name:atrium
config_file: '/home/javi/rock/dev/bundles/eds/config/data/atrium/atrium.yaml'
# Simple calibration since this is a simulated pinhole camera model
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/atrium/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.001
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.020
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.001
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.05
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

# STEREO DAVIS DATASET ECCV18 (Used in the paper)
--- name:bin
config_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/bin/bin.yaml'
# Calibration parameters for the DAVIS took from https://rpg.ifi.uzh.ch/ECCV18_stereo_davis.html
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/bin/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.05
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.001
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.05
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

--- name:boxes
config_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/boxes/boxes.yaml'
# Calibration parameters for the DAVIS took from https://rpg.ifi.uzh.ch/ECCV18_stereo_davis.html
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/boxes/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.05
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.001
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

--- name:desk
config_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/desk/desk.yaml'
# Calibration parameters for the DAVIS took from https://rpg.ifi.uzh.ch/ECCV18_stereo_davis.html
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/desk/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.05
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.001
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.05
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

--- name:monitor
config_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/monitor/monitor.yaml'
# Calibration parameters for the DAVIS took from https://rpg.ifi.uzh.ch/ECCV18_stereo_davis.html
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/stereo_davis/monitor/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.05
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.001
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.05
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

# SNOOPY EXTRA SEQUENCES (01_CALIB)
--- name:snoopy
# You can download this sequence by running:
# wget https://download.ifi.uzh.ch/rpg/eds/extra_sequences/snoopy/snoopy.log
config_file: '/home/javi/rock/dev/bundles/eds/config/data/extra_sequences/snoopy/snoopy.yaml'
# Remember this file has to be a symbolic link to 01_calib/camchain-mediajaviJAVISdatasetshwdscalibratione2kalibr.yaml in bundles/eds
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/dual_setup/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.030
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.0008 # > 1KHz
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.001
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 1.0
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5

# EDS RELEASE DATASETS (03_CALIB)
--- name:11_all_characters
config_file: '/home/javi/rock/dev/bundles/eds/config/data/eds_dataset/11_all_characters/11_all_characters.yaml'
# Remember that this file has to be a symblic link to 03_calib/camchain-mediajaviJAVISdatasetshwdscalibratione2kalibr.yaml in bundles/eds
calib_file: '/home/javi/rock/dev/bundles/eds/config/data/dual_setup/camera_info.yaml'

# minimum time, in s, between two sequential samples arrive on events
events_period: 0.00005 # approx 20KHz
# minimum time, in s, between two sequential samples arrive on frame
frame_period: 0.017 #>50Hz 
# minimum time, in s, between two sequential samples arrive on imu
imu_period: 0.0008 # > 1KHz
# minimum time, in s, between two sequential samples arrive on ground_truth
groundtruth_period: 0.006
# Maximum time in seconds the transformer will wait until it starts dropping samples
aggregator_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
stream_aligner_status_period: 0.5
